groups:
  - name: alert_rules
    rules:
      - alert: High_CPU
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 2m
        annotations:
          summary: "🔥 CPU élevé: {{ $value | printf \"%.1f\" }}%"
          description: "Le processeur tourne à {{ $value | printf \"%.1f\" }}% depuis 2 minutes"